### ISSUE TITLE
Board Assembly Drawing - discussion

### ISSUE THREAD

**Issue by fitzfish** [feilipu/yaz180#4]
Hello feilipu,

It would be very helpful if you could generate a pdf or png file of the assembly drawing from the PCB design tool you use for your PCB v2.2. If this is not clear, I am speaking of a picture with the board outline, pads, silkscreen outlines and reference designators visible to aid in correctly locating the component locations during assembly for those small components that do not have a reference designator visible on the final boards. I do not have your PCB tool and therefore cannot generate the view. 

As an example, you generated this for V2 here: https://feilipu.me/2017/02/26/yet-another-z180-v2/names/#main

Thank you again and best regards,
Dave

**Comment by feilipu** [comment]
Sorry for the oversight. This was something that I thought I had done some time ago, and yet it was not done. I have added the [Values and Names](https://github.com/feilipu/yaz180/commit/d36a0f9c51e5b9f19539bef81534c498ae4ce55f) PDFs for both V22 and V21. I hope that is useful.

Also, I added a [small update into the construction notes](https://github.com/feilipu/yaz180/commit/ddfe1b934e9c4ec652cbaee51bc79c4be4d3b8ea) about running the YAZ180 at 36.864MHz, and the timing for the Am9511A. Essentially a small jumper from Pad 11 to Pad 8 is needed on the 74LS93 so that the Am9511A `CLK` is driven at 1/16 of `PHI`, rather than 1/8 of `PHI`. The [code changes](https://github.com/feilipu/yaz180/commit/7fbc5e77df48c66f6f10bc803db100c76a4b742d) around this fix have already been made.

I'll leave this issue open, and if there's anything else I can help with, just let me know.
Phillip

**Comment by fitzfish** [comment]
Above and beyond Phillip. Exactly what was needed! Thank you. 

I made an oversight of a few parts when ordering and will have them midweek or sooner. I will be building again then and appreciate the support. 

Best regards,
Dave

**Comment by feilipu** [comment]
I'm pretty amateur when it comes to SMD, and it often takes me a few tries to get the RAM chip in right. The issue with that is that it is the most expensive device to replace. My only advise is to take your time.
Same with the USB and I2C devices.

Of course if you know what you're doing, then you'll probably have better  luck than I have.
So, good luck with your building process. :+1: 

Hope to hear the results, in due course.

**Comment by fitzfish** [comment]
I had similar problems with that part specifically, but also others to a lesser extent. On the ram - the circuit board as delivered does not include solder mask between the pads. This makes it virtually certain that solder bridging will occur during assembly. You could reduce the pad width a few mil to ensure the PCB vendor can adequately screen soldermask in there if you ever have to revise the board in the future. De-solder braid is my friend...

Overall a very nice layout and the assembly drawing has helped immensely. Thank you! 

Remaining parts are on the truck for delivery today.
Best regards,
Dave

**Comment by fitzfish** [comment]
Phillip,

Assembly complete and in testing. One has a short on 5V that I am still chasing. Noting obvious visible so am looking over once again.

The second board is powering up. I have found a couple of issues that were preventing it from coming out of reset and assume this is a good place to bring them up -

1. There is on open input on IC8 pin 5. Needs to be pulled up or will prevent coming out of reset (at least on the hardware build here). 
2. I do not yet have an APU. The PAUSE signal is un-terminated when no APU installed which prevents the system from coming out of reset A 10k pull up to 5V under the 16V8 fixed this. 
3. One final issue comes from the FT485. /RXE powers up low while RD and USB_CS power up high, causing Wait to be asserted from IC6. Not sure if this is a logic issue or something else. Applying 5V to the USB connector for that channel briefly brings the FT485 out of reset long enough for that signal to clear. 

The board now comes out of reset and I can see the address display scrolling along. I have attempted to connect to a terminal to see if anything is talking with both the CPM and standard implementations for the BIOS and have gotten no further. Time to dig deeper into the BIOS for insight into the terminal settings. Any help there is appreciated to kick start progress! My desire is to run the test utilities you created next! 

I hope the feedback helps and please know that I appreciate you blazing the trail for us here who wish to follow!

Best regards,
Dave

**Comment by feilipu** [comment]
Dave,

thanks for the inputs.

The PCB doesn't have solder mask on the RAM, but it was ordered with "Solder Dam". I think the purpose of this solder dam is to reduce the chances of flow between the pads. Still, I find it ineffective.

The only way I can get the RAM to solder correctly is to wet the pads before the oven (with no device), and then later clean and re-tin them with fine tipped solder iron. Then lay the RAM device and hold it down, solder the diagonals, then solder the rest pressing on each pin with fine tweezers to hold it until solder hardens. Quite slow, and there must be a better way.

> There is on open input on IC8 pin 5. Needs to be pulled up or will prevent coming out of reset (at least on the hardware build here).

Noted. I'll fix this for the next iteration.

> I do not yet have an APU. The PAUSE signal is un-terminated when no APU installed which prevents the system from coming out of reset A 10k pull up to 5V under the 16V8 fixed this.

Hmm. The GAL devices are supposed to have active pull ups on all input pins. At least that is what is advertised. Although they also recommend terminating inputs, so adding a pull up resistor is a good idea.

> One final issue comes from the FT245R. `/RXE` powers up low while `/RD` and `USB_CS` power up high, causing Wait to be asserted from IC6. Not sure if this is a logic issue or something else. Applying 5V to the USB connector for that channel briefly brings the FT245R out of reset long enough for that signal to clear.

I think all the points above are probably fixed once powered up. Everything works following a clean, powered up, `RESET` signal, which will also reset the GAL and USB devices. I find my YAZ180 boards won't run from power on, and some of above is probably the reason why this is the case.

Let me know if you can get yours working from power up without a press on the `RESET` button, please.

EDIT, I've added an [owner notes](https://github.com/feilipu/yaz180/blob/master/owners_notes.md) section too. Perhaps that will be useful.

Phillip

**Comment by fitzfish** [comment]
Hi Phillip,

>Hmm. The GAL devices are supposed to have active pull ups on all input pins. At least that is what is advertised. Although they also recommend terminating inputs, so adding a pull up resistor is a good idea.

Makes sense. I chose a different manufacturer 16V8. Specifically Atmel's ATF16V8C. Likely does not have those pull up terminations. Seems the only one needed to make it work.

>Let me know if you can get yours working from power up without a press on the RESET button, please.

I did! The issue here was that the signals out of the FT485 need to be reset initially to work with the logic PAL. I added an 1N4148 diode to create an OR for the reset signal to the FT485. The anode connects to pin 1 of U16. This is the active high system reset. The cathode connects to the /FTDI1_RESET at the junction of R11 and R14. Using the active high reset signal allows the FT485 chip to come out of reset just long enough for /RXE to go inactive. Once system reset is inactive again the FT485 is back held in reset until connected to an external USB port and the board is no longer held in wait. 

Works now every time from power up here.

Thank you for the owner notes. Excellent! 

I'm traveling the next week or so. Look forward to picking it up again after I return.
Best regards and thank you,
Dave

**Comment by feilipu** [comment]
I've just finished a [V2.3 of the YAZ180](https://github.com/feilipu/yaz180/tree/master/pcb/V23_20181120), and I'll start building it up over the holiday season for 2019.

It incorporates your fix as per below, plus all the other issues identified in the [construction notes](https://github.com/feilipu/yaz180/blob/master/construction_notes.md). Thanks again for debugging this issue. The resolution was not obvious.

> I added a 1N4148 diode to create an OR for the reset signal to the FT245R. The anode connects to Pin 1 of U6. This is the active high system `RESET`. The cathode connects to the `/FTDI1_RESET` at the junction of R11 and R14. Using the active high reset signal allows the FT245R chip to come out of reset just long enough for `/RXE` to go inactive. Once system reset returns inactive then the FT245R is held in reset until connected to an external USB port, and the board is not longer held in wait.

I elected not to add the pull-up resistor for the `PAUSE` line. In the seldom case where the APU is not going to be equipped a through hole pull-up resistor can be added easily. So, it is not really necessary to provision another resistor to the BOM.

I'm planning to build up a few new V2.3 boards and then see whether they [sell on Tindie](https://www.tindie.com/products/feilipu/yaz180-pcb-modern-single-board-z80-computer/) early next year. If they do, then I'll keep building them in any spare time.

**Comment by feilipu** [comment]
For some reason the Gerber dimension information was not respected in the V2.3 PCBs, and also I couldn't get the build on the (incorrectly sized) PCB to work. So, I revised to make a V2.4 PCB.

The V2.4 PCBs (there are only 5 currently) have all been built and are working. Once I'm 100% satisfied with the testing, then I'll sell them on Tindie, and also order some more raw PCBs.

So, I'll close this issue now. Thanks again for helping to make the YAZ180 better.
